# Social Computing - Summer 2017
# Exercise 4 - Clustering

## Problem 4.1. K-means Clustering of couse network data

Write a Python program that computes K-means clustering for the course dataset. The input dataset (file: networkinput.csv) contains data from our social networking platform. As always this data has been anonymized. Each line in the file represents one feature vector and is associated with a participant in the social networking platform. The vectors have a name ("userXYZ") and the following 4 features:
* Number of posts
* Number of comments
* Number of likes (on both posts and comments)
* Number of friends and followers (average)

By clustering the participants, you identify particpants with similar activity patterns. This can be helpful for research but also for advertisers and polling firms.

Your program should compute K-means clustering for the dataset according to the formula discussed in the lecture ==> Minimizing the objective function:
$$\sum_{k=1}^{K} \sum_{\{n|x_n \in C_k \}} \|x_n - \mu_k\|^2$$
Such that:
$K$ is the number of clusters, $x_n$ is the nth point that belongs to the $k$th cluster, and $\mu_k$ is the centroid (prototype) of the $k$th cluster. (Refer to the lecture for details)
The K-means clustering algorithm should proceed as follows:
1. The program should start by parsing the dataset 
2. Assign four random centroids (prototypes).
3. Assign data points to the nearest centroid. 
4. Recompute the centroid values: The new centroid values of the kth centroid are calculated as the average values of the points currently in that centroid.
5. Repeat from point 3 till the values of the centroids don't change anymore.

<b>The output of your program should be a a list that asigns a cluster ID (0, 1, 2, 3) to every user in the input file. </b>
The first argument in that tuple should be the users's name (e.g., "user111") and the second argument should be the centroid id to which this user is associated to. e.g ('user111', 3).
**Note:** this output value should be the final centroid values that don't change anymore.


<b> After the clustering with k=4 is complete, run the code with the following centroid starting points:

centroids = {0: [9, 33, 29, 25], 1: [4, 44, 12, 41], 2: [10, 13, 44, 65], 3: [10, 44, 48, 70]}.

Have a look at the result and describe the common properties in each of the four groups</b> (max 5 sentences).


In [17]:
import csv 
import random 
import numpy as np 
from scipy.spatial import distance 

# TODO: Read the network activity data set into a dictionary (observations_dictionary)
def read_data_set():
    observations_dictionary = {}
    dataFromCSV = csv.reader(open('networkinput.csv'))
    for row in dataFromCSV:
        key = row[0]
        row[1]=float(row[1])
        row[2]=float(row[2])
        row[3]=float(row[3])
        row[4]=float(row[4])
        observations_dictionary[key] = row[1:]
    return observations_dictionary



# TODO: Assign random centroids
# Hint: centroid values should be randomly assigned so that for each dimension of the centroid, the random values should fall
# between the maximum and the minimum value of that dimension of all the points in the data set.
# For example: for the dimension "Number of Comments", if the maximum value = 49, and the minimum value = 0, the value assigned to
# the dimension "Murder" of the centroid should be randomly assigned between 0 and 49
def create_random_centroid_values(observations):
    # find min and max of observations in each dimension
    # create dictionary with four random centroids within the observed space
    posts = []
    comments = []
    likes = []
    friends = []
    centroid = {}
    for value in observations.values():
        post_dimension.append(value[0])
        comment_dimension.append(value[1])
        likes_dimension.append(value[2])
        friends_dimension.append(value[3])
    #Calculating Minimum Values for all four dimensions
    minPosts= min(posts)  
    minLikes = min(likes)
    minComments= min(comments)
    minFriends = min(friends)
    
    #Calculating Maximum Values for all four dimensions
    maxPosts= max(posts)
    maxComments = max(comments)
    maxLikes = max(likes)
    maxFriends = max(friends)
    
    #Gererating a centroid point by picking a random number between min and max of each dimension
    i=0
    while i < 4:
        randomCentroid = []
        randomCentroid.append(random.randint(minPosts,maxPosts))
        randomCentroid.append(random.randint(minComments,maxComments))
        randomCentroid.append(random.randint(minLikes,maxLikes))
        randomCentroid.append(random.randint(minFriends,maxFriends))
        centroid[i]= randomCentroid
        i+=1
    return  centroid   
    
        
    
# Assign centroid ID for each of the data points. Each data item is assigned to its closest centroid
def update_observation_centroids(observations, centroid, k, observation_centroids = None):
    # create dictionary mapping each observation to a centroid index
    if observation_centroids == None: 
        # initial run: For each centroid i of the k centroids, create random values
        #create_random_centroid_values(observations, centroid_i)
        
        observation_centroids = {} 
        c0 = np.array(centroid[0])
        c1 = np.array(centroid[1])
        c2 = np.array(centroid[2])
        c3 = np.array(centroid[3])
        print c0,c1,c2,c3
        for point in observations:
            x = np.array(observations[point])
            dist1 = distance.euclidean(x,c0)
            dist2 = distance.euclidean(x,c1)
            dist3 = distance.euclidean(x,c2)
            dist4 = distance.euclidean(x,c3)

            low_dist = dist1
            cluster_id=0
            
            if(low_dist>dist2):
                low_dist = dist2
                cluster_id=1
            if(low_dist>dist3):
                low_dist = dist3
                cluster_id=2
            if(low_dist>dist4):
                low_dist=dist4
                cluster_id=3
            observation_centroids[point]=cluster_id
            
    return observation_centroids# TODO: return the updated centroids
    
    # Otherwise
    #for key in observations:
        # TODO: Each centroid i of the K centroids is the average of the data values previously assigned to that centroid i
    
    #return # TODO: Return the newly created observation centroids


# Create new centroid values for each cluster as the mean of data values for the points in that cluster 
# Create new centroid values for each cluster as the mean of data values for the points in that cluster 
def update_centroid_values(observations, observation_centroids, k):
    centroid1_list = []
    centroid2_list = []
    centroid3_list = []
    centroid4_list = []
    
    for item in observation_centroids:
        if(observation_centroids[item]==0):
            centroid1_list.append(item)
        if(observation_centroids[item]==1):
            centroid2_list.append(item)
        if(observation_centroids[item]==2):
            centroid3_list.append(item)
        if(observation_centroids[item]==3):
            centroid4_list.append(item)
    
    #calculate new centroid 1
    new_centroid = {}
    post_dimension = []
    comment_dimension = []
    likes_dimension = []
    friends_dimension = []
    for item in centroid1_list:
        post_dimension.append(observations[item][0])
        comment_dimension.append(observations[item][1])
        likes_dimension.append(observations[item][2])
        friends_dimension.append(observations[item][3])
    l= []
    if(len(post_dimension)!=0):
        l.append(np.mean(post_dimension))        
        l.append(np.mean(comment_dimension))
        l.append(np.mean(likes_dimension))
        l.append(np.mean(friends_dimension))
    else:
        l=[0.0,0.0,0.0,0.0]
    new_centroid[0] = l
    
    #calculate new centroid 2
    post_dimension = []
    comment_dimension = []
    likes_dimension = []
    friends_dimension = []
    for item in centroid2_list:
        post_dimension.append(int(observations[item][0]))
        comment_dimension.append(int(observations[item][1]))
        likes_dimension.append(int(observations[item][2]))
        friends_dimension.append(int(observations[item][3]))
    l=[]
    if(len(post_dimension)!=0):
        l.append(np.mean(post_dimension))
        l.append(np.mean(comment_dimension))
        l.append(np.mean(likes_dimension))
        l.append(np.mean(friends_dimension))
    else:
        l=[0.0,0.0,0.0,0.0]
    new_centroid[1] = l
    
    #calculate new centroid 3
    post_dimension = []
    comment_dimension = []
    likes_dimension = []
    friends_dimension = []
    for item in centroid3_list:
        post_dimension.append(int(observations[item][0]))
        comment_dimension.append(int(observations[item][1]))
        likes_dimension.append(int(observations[item][2]))
        friends_dimension.append(int(observations[item][3]))
    l= []
    if(len(post_dimension)!=0):
        l.append(np.mean(post_dimension))
        l.append(np.mean(comment_dimension))
        l.append(np.mean(likes_dimension))
        l.append(np.mean(friends_dimension))
    else:
        l=[0.0,0.0,0.0,0.0]
    new_centroid[2] = l
    
    #calculate new centroid 4
    post_dimension = []
    comment_dimension = []
    likes_dimension = []
    friends_dimension = []
    for item in centroid4_list:
        post_dimension.append(int(observations[item][0]))
        comment_dimension.append(int(observations[item][1]))
        likes_dimension.append(int(observations[item][2]))
        friends_dimension.append(int(observations[item][3]))
    l= []
    if(len(post_dimension)!=0):
        l.append(np.mean(post_dimension))
        l.append(np.mean(comment_dimension))
        l.append(np.mean(likes_dimension))
        l.append(np.mean(friends_dimension))
    else:
        l=[0.0,0.0,0.0,0.0]
    new_centroid[3] = l
    return new_centroid

def calculate_k_means_clustering(data_set_path, k):
    observations = read_data_set()
    #new_centroids = create_random_centroid_values(observations)
    #print centroids
    new_centroids = {0: [9, 33, 29, 25], 1: [4, 44, 12, 41], 2: [10, 13, 44, 65], 3: [10, 44, 48, 70]}
    centroids = None
    # TODO: Compare the new centroid dictionary with the old centroid dictionary
    i=0
    while centroids != new_centroids :# new and old centroid dictionaries are NOT similar, do:
        i+=1
        #print new_centroids
        centroids = new_centroids
        observation_centroids = update_observation_centroids(observations, centroids, k)
        new_centroids = update_centroid_values(observations, observation_centroids, k)
    print centroids
    print new_centroids
    print i
    
    centroid1_list = []
    centroid2_list = []
    centroid3_list = []
    centroid4_list = []
    for item in observation_centroids:
        if(observation_centroids[item]==0):
            centroid1_list.append(item)
        if(observation_centroids[item]==1):
            centroid2_list.append(item)
        if(observation_centroids[item]==2):
            centroid3_list.append(item)
        if(observation_centroids[item]==3):
            centroid4_list.append(item)
    print len(centroid1_list)
    print len(centroid2_list)
    print len(centroid3_list)
    print len(centroid4_list)
        
        
# run code
calculate_k_means_clustering('networkinput.csv', 4)

[ 9 33 29 25] [ 4 44 12 41] [10 13 44 65] [10 44 48 70]
[ 0.44204852  3.01617251  3.54716981  4.85175202] [ 0.  0.  0.  0.] [  0.5   9.5  33.5  48. ] [  7.5  38.   56.   59.5]
[ 0.81460674  5.62921348  6.20786517  7.65730337] [ 0.          0.1657754   0.04278075  1.5828877 ] [  2.5    13.125  33.75   29.625] [  7.5  38.   56.   59.5]
[ 1.08333333  7.3         8.04166667  8.85      ] [ 0.05371901  0.48760331  0.25619835  2.31818182] [  2.          13.09090909  32.36363636  24.81818182] [  7.5  38.   56.   59.5]
[ 1.19387755  7.86734694  8.71428571  9.2244898 ] [ 0.05747126  0.73180077  0.36015326  2.65517241] [  2.46153846  12.61538462  29.38461538  19.38461538] [  5.33333333  29.33333333  55.          55.33333333]
[ 1.15053763  7.91397849  8.52688172  9.44086022] [ 0.05681818  0.76893939  0.37121212  2.73106061] [  2.8         12.46666667  29.26666667  16.66666667] [  5.33333333  29.33333333  55.          55.33333333]
[ 1.01136364  7.94318182  7.75        9.54545455] [ 0.05681818  0.76

In [ ]:
The goal of this algorithm is to find groups in the data, with the number of groups represented by the variable K. The algorithm works iteratively to assign each data point to one of K groups based on the features that are provided. Data points are clustered based on feature similarity.
In this experiment, we see that people with same number of posts, people who like to comment, people with more likes and people with friends are grouped spearately. K-means algoritham clusters groups and we can find a behaviourial pattern in those groups.

## Optional: Problem 4.2. Girvan-Newman Algorithm 
The Girvan-Newman algorithm is an efficient algorithm for computing graph clustering.

Write a Python program that computes the best clustering for the Krackhardt Kite graph.
Remember from the lecture that the central idea of the Girvan-Newman algorithm is to compute the edge betweenness in the input graph. Large betweenness value is an indication that the corresponding edge is a bridge between two clusters in the graph, and cutting that edge means isolating those clusters.
The algorithm proceeds by determining edge betweenness values for all the edges in the graph, and removing the edge with the highest betweenness value and repeating until there are no more edges.
The output of the Girvan-Newman algorithm is a dendrogram of clusters where individual vertices are at the bottom. Therefore, it's necessary to cut that dendrogram and determine the best cluster. Best clustering is the one with the highest graph modularity value, which is determined by the formula:
$$ Q = \sum_{i} (e_{ii} - a_i^2) $$
where $e_{ii}$ sums the fraction of graph edges that connects nodes in the ith cluster. And $a_i$ is the fraction of edges that connect to the ith cluster (see lecture for details)
The input to the Python program will be the Krackhardt Kite Graph as an igraph Graph object. The output should be a tuple of two arguments:
The first should be the value of the best modularity corresponding to the best graph clustering (a floating point number). The second argument should be a tuple of igraph Graph objects representing the clusters. 
HINT: The edge betweenness calculation is a variation of the Ulrik Brandes algorithm for calculating betweenness centrality (exercise 1). The attached paper explains how to modify the algorithm to calculate edge betweenness.

In [ ]:
import igraph
import Queue
from __future__ import division
import numpy as np


def calculate_node_degrees(g):
    # HINT: You will need to calculate the adjacency matrix of the graph
    # Some Graph methods from igraph could be helpful

def calculate_modularity(g, original_deg_dict, m):
    modularity = 0
    degree_dict = calculate_node_degrees(g)
    connected_components = g.components()
    for i in range(len(connected_components)):
        subgraph = connected_components.subgraph(i) # each subgraph represents a cluster in the graph
        e = 0 # Fraction of edges that connect to cluster
        a = 0 # Fraction of edges that connect to cluster with random connections between edges
        for v in subgraph.vs:
            e += degree_dict[v.index]
            a += original_deg_dict[v.index]
        # TODO: Calculate the modularity
    return modularity
        
# TODO: Calculate edge betweeness  
def calculate_edge_betweenness(g):

def calculate_girvan_newman_clustering(g):
    m = # TODO: The original number of edges
    original_degree = calculate_node_degrees(g)
    while # TODO: Graph still has edges:
        Q = calculate_modularity(g, original_degree, m)
        if (Q > largest_modularity):
            largest_modulatirty = Q
            edge_betweenness = calculate_edge_betweenness(g) # TODO: get edge with the highest betweenness value
            # TODO: delete the edge with the maximum betweenness value
            # Hint: Some built-in methods from igraph could be helpful
    
    # Finally
    return final_graph_clustering, largest_modularity

# Program's entry point:
g = igraph.Graph.Famous('Krackhardt_Kite') # Connected, Unweighted, undirected social network
calculate_girvan_newman_clustering(g)